main:
  project_name: "iris_demo"
  experiment_name: "development"
  steps: "all"
download:
  uri: "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
  artifact_name: "iris.data"
  artifact_type: "raw_data"
  artifact_description: "raw file as downloaded"
clean:
  input_artifact: "iris.data:latest"
  output_artifact: "iris.csv"
  output_type: "clean_data"
  output_description: "cleaned data"
  col_names: "sepal_length,sepal_width,petal_length,petal_width,species"
