main:
  project_name: "iris_demo"
  experiment_name: "development"
  steps: "all"
download:
  uri: "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
  artifact_name: "iris.data"
  artifact_type: "raw_data"
  artifact_description: "raw file as downloaded"
clean:
  input_artifact: "iris.data:latest"
  output_artifact: "iris.csv"
  output_type: "clean_data"
  output_description: "cleaned data"
  col_names: "sepal_length,sepal_width,petal_length,petal_width,species"
split:
  input_artifact: "iris.csv:latest"
  test_size: 0.3
  random_seed: 42
  file_names: "iris_train.csv,iris_test.csv"
train:
  train_data: "iris_train.csv:latest"
  target: "species"
  model_config: "model_config.json"
  model_name: "model.joblib"
